## Namespace of the robot
namespace: "simple_1dof"      # defaul = "toBEassigend"

## Sample time for the node
T_sample: 0.002               # NOT used yet!  

## Control type for the joints (TODO: make an array for different control on joints)
control_type: 3               # controller type [0] for motors position (default)
                              #                 [1] for eq. position/preset,
                              #                 [2] for joint torques,
                              #                 [3] (NOT used yet!) for motors references taken from the other plugin.